export const HOOSAT_PARAMS = {
  ADDRESS_PREFIX: 'hoosat',
  SIGHASH_ALL: 0x01,
  SIGHASH_NONE: 0x02,
  SIGHASH_SINGLE: 0x04,
  SIGHASH_ANYONECANPAY: 0x80,
  COINBASE_MATURITY: 100,
  DEFAULT_FEE_PER_BYTE: 1,
  MIN_FEE: 1000,
  SUBNETWORK_ID_NATIVE: Buffer.alloc(20, 0),
} as const;
